# width of the border around windows, in px
border_width = 3

# colour of the border of focused windows, in hex
border_focused = "#a9a9a9" # colours can either be in the form #RRGGBB...

# colour of the border of unfocused windows, in hex
border_unfocused = "808080" # ...or RRGGBB

# mod key to be used in keyboard shortcuts
mod_key = "Mod4" # Meta key

# default layout that will be applied to all workspaces at startup
default_layout = "masterstack"

# gaps
gaps_inner = 10
gaps_outer = 10

# apps that will be run at startup
startup = [
  "polybar",
  "kitty",
]

keybinds = {
  "mod+shift+q" = "quit",
  "mod+w" = "focus next",
  "mod+c" = "closewindow",

  "mod+return" = "exec kitty",
  "mod+r" = "exec rofi -show run",

  "mod+1" = "setworkspace 1",
  "mod+2" = "setworkspace 2",
  "mod+3" = "setworkspace 3",
  "mod+4" = "setworkspace 4",
  "mod+5" = "setworkspace 5",

  "mod+m" = "setlayout monocle",
  "mod+s" = "setlayout masterstack",
  "mod+shift+c" = "setlayout columns",
  "mod+shift+s" = "exec flameshot gui"
}
