# width of the border around windows, in px
border_width = 2

# colour of the border of focused windows, in hex
border_focused = "ff0000" # red

# colour of the border of unfocused windows, in hex
border_unfocused = "ffffff" # white

# the mod key to be used
mod_key = "Mod4"

# gaps
gaps_inner = "10"
gaps_outer = "10"

# the default layout that will be applied to each workspace
default_layout = "masterstack"

# commands that will be executed at startup
startup = [
    "polybar",
    "kitty"
]

# keybinds
# format: "modifiers+key" = "action parameters"
keybinds = [
    "mod+shift+q" = "quit",
    "mod+w" = "focus next",
    "mod+c" = "closewindow",

    "mod+enter" = "exec kitty",
    "mod+r" = "exec rofi -show run",

    "mod+1" = "setworkspace 1",
    "mod+2" = "setworkspace 2",
    "mod+3" = "setworkspace 3",
    "mod+4" = "setworkspace 4",
    "mod+5" = "setworkspace 5",
]
