name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Init
      run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev
    - name: Build
      run: cargo build --verbose
    # skip tests - i don't have any unit tests
    # - name: Run tests
    #  run: cargo test --verbose
